modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
# A URL to refer people to when problems occur with this mod
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]] #mandatory
modId="tinkers_rpg"
version="${tinkers_rpg_version}" #mandatory
 # A display name for the mod
displayName="Tinkers RPG" #mandatory
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
logoFile="pack.png" #optional
credits="Thanks to all the Tinkers out there. Keep tinkering!"
authors="ChiefArug" #optional
description='''
An attempt at turning Tinkers Construct into an RPG.
'''
[[dependencies.tinkers_rpg]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${forge_range}" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.tinkers_rpg]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.tinkers_rpg]]
    modId="tconstruct"
    mandatory=true
    versionRange="${tinkers_range}"
    ordering="AFTER"
    side="BOTH"
